version: '3'
services:
  frontend:
    build: ./frontend
    image: shehabfahmy/nti-final-project-frontend:latest
    ports:
      - "8181:80"
    depends_on:
      - backend
    networks:
      - front-tier
      
  backend:
    build: ./backend
    image: shehabfahmy/nti-final-project-backend:compose
    ports:
      - "8282:3001"
    depends_on:
      - mongo
    networks:
      - front-tier
      - back-tier
  
  mongo:
    image: "mongo:latest"
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - "./db-data:/data/db"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
